### PR TITLE
Friend habit events page

### PR DESCRIPTION
**Pull request by Matheus-Du**
UI for Friend Habit Event Page (issue #20). 
Users can navigate to page by clicking the "View Friend's Habit For Today" button in My Friends page.
Figma diagram doesn't have this page so UI layout may need updates. For instance, I can add a textview for friend's username for each habit. Will update Figma when merged.

### CODE REVIEW

**Review by adiep2 — CHANGES_REQUESTED** [review]
Two small formatting issues, the first one needs to be fixed (the button is covering the nav bar).  The second one is not as important, but the completed list is very small (I think it is a phone screen size problem).  Besides that looks good just these small fixes and I will approve
image
image

**Comment by Matheus-Du** [comment]
> Two small formatting issues, the first one needs to be fixed (the button is covering the nav bar). The second one is not as important, but the completed list is very small (I think it is a phone screen size problem). Besides that looks good just these small fixes and I will approve image image

Should be resolved. If not LMK what emulator you're using and I will try and find the issue using it.

**Review by adiep2 — APPROVED** [review]
Looks good!

**Review by ccchoi2 — APPROVED** [review]
All look good 👍

**Pull request merged**
