### PR TITLE
Location feature

### PR DESCRIPTION
**Pull request by hibaqw**
Set up tentative HabitLocation class to store address, name, and coordinates of user location. Autocomplete search should allow users to search location. Also determines the location of the device. There is something off with my emulator so please test that it successfully determines your location. If you run it, it should open with a map with a marker on top of your location....

### CODE REVIEW

**Comment by Ryden-Graham** [comment]
Can you connect this to something on the GUI so we can open it? (no need for backend connections yet)

**Review by adiep2 — CHANGES_REQUESTED** [review]
A couple changes are needed.
1. The divide by zero on the main page was fixed in another PR so please revert that and pull/merge from main.
2. In the image below, the button on the bottom is slightly off center and blocks the other Google buttons
3. Not sure what the aforementioned button does is it supposed to set Location? The button doesnt do anything for me.
Everything else looks fine, the map and search bar work well.
image

**Review by adiep2 — CHANGES_REQUESTED** [review]
I think you accidently took out the FriendHabits and FriendsHabitEventsPage out of the android manafest by accident they need to be re-added in.
Also the button icon is still off center and covers the other google buttons, if you cant change this thats ok (I am using a Pixel XL for the emulator if you are wondering)

**Review by adiep2 — APPROVED** [review]
Looks good!

**Review by Ryden-Graham — APPROVED** [review]
Looks good.

I would recommend we make selecting a location also close the fragment, but we can add that later.

**Comment by hibaqw** [comment]
Updating main with location feature...

**Pull request merged**
