### PR TITLE
User profile page

### PR DESCRIPTION
**Pull request by Matheus-Du**
Implementation of UI for user profile page and edit profile fragment as per issue #14.

clicking "go to user profile" on the loginscreentest page will redirect to the user profile page which should have all needed elements implemented. Pressing the settings icon in the top right of the screen will open the profile settings page, containing UI elements to update profile photo and username. Pressing the 'save and exit' button will simply close the fragment, while pressing 'exit without saving' will open a dialog prompt asking the user to confirm closing the fragment without saving their changes.

The completion percentage textView's background will change colours depending on the percentage of habits completed.

### CODE REVIEW

**Review by Ryden-Graham — APPROVED** [review]
Looks great! Love the confirmation box for exiting without saving!

**Review by adiep2 — CHANGES_REQUESTED** [review]
This is what I see on the edit profile page when I try to edit the name.  I think it has to do with the screen size of my emulator (Pixel XL).  Everything else looks fine, send a rereview request after this is fixed and I can approve.
image

**Comment by Matheus-Du** [comment]
Fixed bug in PixelXL emulator causing nav buttons to wrap to top of keyboard, causing buttons to block username input field

**Review by adiep2 — APPROVED** [review]
Good job on the bug fix looks good.

**Pull request merged**
